apiVersion: v1
kind: Service
metadata:
  name: my-python-service
  namespace: preproduction
spec:
  selector:
    app: products-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
